### PR TITLE
feat: create account archival

### PR DESCRIPTION
**Pull request by DaeunYoon**
image
image

- need to replace to actual text

### CODE REVIEW

**Review by valiafetisov — COMMENTED** [review]
I also suggest to include into this PR:

- [ ] limiting of minimum parts and minimum threshold by 2
- [ ] setting default values to be 3 parts, 2 minimum
- [ ] splitting of the private key using one line `split(Buffer.from(privateKey), { shares: 3, threshold: 2 })` from [shamirs-secret-sharing-ts](https://www.npmjs.com/package/shamirs-secret-sharing-ts) package
- [ ] downloading of text file on button click (by replacing button with `<a>` tag and adding `href` attribute with value of `URL.createObjectURL(new Blob([sharedSecret], {type: 'text/plain'}))` and `download` attribute with `shared-secret.txt`)

Feel free to skip if anything of this doesn't work for you

**Review by LukSteib — CHANGES_REQUESTED** [review]
- [ ] Removing inputs via dedicated x-icon results in error crashing the component (see e1) 
- [ ] do we want to add a loading state when increasing the number of shared secrets count (assuming pdf generation would take some time later). Or is this already present? 


e1
`TypeError: Expecting shares to be a number.`

**Comment by DaeunYoon** [comment]
>  do we want to add a loading state when increasing the number of shared secrets count (assuming pdf generation would take some time later). Or is this already present?

I'd expect `pdf generation` to happen after clicking the download button. and if that's the case there's `loading` simulation for it existing now :)

**Comment by valiafetisov** [comment]
> I'd expect pdf generation to happen after clicking the download button.

Actually, the idea was, if look into the mocks, that when the panel is just opened, it generates the PDF. But I think it's fine for the initial version 🙂

**Review by LukSteib — APPROVED** [review]

**Review by valiafetisov — COMMENTED** [review]
Before I merge it, because the code is quite complicated and I can't figure it out by reading: if I dowloaded one PDF, but then changed the number of parts (eg from 3 to 4 parts), would first download button keep being recorded as "downloaded"? Because this is a problem

**Comment by LukSteib** [comment]
> would first download button keep being recorded as "downloaded"?

I've tested this exact flow and as the recording of download was removed in this case it was fine for me.

**Pull request merged**
